
development:
    adapter: postgresql
    host: localhost
    database: e-verification_development
    username: postgres
    password: safew

test:
    adapter: postgresql
    host: localhost
    database: e-verification_test
    username: postgres
    password: safew

production:
    adapter: postgresql
    host: localhost
    database: e-verification_production
    username: postgres
    password: safew
    reconnect: true
