development:
    adapter: postgresql
    host: localhost
    database: e-verification_development
    username: sudhir
    password: sudhirsb


production:
    adapter: postgresql
    host: localhost
    database: e-verification_production
    username: yogesh
    password: yogesh1985
