
development:
    adapter: postgresql
    host: localhost
    database: e-verification_development
    username: desidime
    password: desidime123

test:
    adapter: postgresql
    host: localhost
    database: e-verification_test
    username: desidime
    password: desidime123

production:
    adapter: postgresql
    host: localhost
    database: e-verification_production
    username: desidime
    password: desidime123
    reconnect: true
