
development:
    adapter: postgresql
    host: localhost
    database: e-verification_development
    username: postgres
    password: scorp

test:
    adapter: postgresql
    host: localhost
    database: e-verification_test
    username: postgres
    password: scorp

production:
    adapter: postgresql
    host: localhost
    database: e-verification_production
    username: postgres
    password: scorp
    reconnect: true
